In [1]:
!pip install h2o mlflow dagshub scikit-learn pandas matplotlib -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 kB 1.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.5/50.5 kB 2.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 266.4/266.4 MB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.2/11.2 MB 117.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 63.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 71.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 273.3/273.3 kB 22.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 265.9/265.9 kB 15.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.2/68.2 kB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 148.8/148.8 kB 13.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 11.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.0/212.0 kB 20.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.9/123.9 kB 13.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.2/132.2 kB 11.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.0/140.0 kB 15.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.6/15.6 MB 85.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 62.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.9/214.9 kB 14.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 6.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.2/90.2 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 7.2 MB/s eta 0:00:00

In [2]:
import h2o
from h2o.automl import H2OAutoML
import pandas as pd
import mlflow
import dagshub

In [4]:

h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "17.0.19" 2026-04-21; OpenJDK Runtime Environment (build 17.0.19+10-1-22.04.2-Ubuntu); OpenJDK 64-Bit Server VM (build 17.0.19+10-1-22.04.2-Ubuntu, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.12/dist-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmpe0o27345
  JVM stdout: /tmp/tmpe0o27345/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmpe0o27345/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  -----------------------------------------------------------------------------------------
H2O_cluster_uptime:         02 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.11
H2O_cluster_version_age:    2 months and 19 days
H2O_cluster_name:           H2O_from_python_unknownUser_yzgr0m
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.168 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null, "colab_language_server": "/usr/colab/bin/language_service"}
H2O_internal_security:      False
Python_version:             3.12.13 final
--------------------------  -----------------------------------------------------------------------------------------

In [6]:
import pandas as pd
data = {
"study_hours": [1,2,3,4,5,6,7,8],
"attendance": [50,55,60,70,75,85,90,95],
"internal_marks": [35,40,45,60,70,75,85,90],
"result": ["Fail","Fail","Fail","Pass","Pass","Pass","Pass","Pass"]
}
df = pd.DataFrame(data)
df.to_csv("dataset.csv", index=False)
print("Dataset created successfully")
df

Dataset created successfully

   study_hours  attendance  internal_marks result
0            1          50              35   Fail
1            2          55              40   Fail
2            3          60              45   Fail
3            4          70              60   Pass
4            5          75              70   Pass
5            6          85              75   Pass
6            7          90              85   Pass
7            8          95              90   Pass

In [7]:
data = pd.read_csv("dataset.csv")
h2o_data = h2o.H2OFrame(data)
h2o_data

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

  study_hours    attendance    internal_marks  result
-------------  ------------  ----------------  --------
            1            50                35  Fail
            2            55                40  Fail
            3            60                45  Fail
            4            70                60  Pass
            5            75                70  Pass
            6            85                75  Pass
            7            90                85  Pass
            8            95                90  Pass
[8 rows x 4 columns]

In [8]:
features = [
"study_hours",
"attendance",
"internal_marks"
]
target = "result"

In [9]:
train, test = h2o_data.split_frame(
ratios=[0.8],
seed=42
)
print("Training Data:")
train.shape
print("Testing Data:")
test.shape

Training Data:
Testing Data:

(0, 4)

In [10]:
from h2o.automl import H2OAutoML

automl = H2OAutoML(
    max_models=10,
    seed=42,
    max_runtime_secs=120
)

automl.train(
    x=features,
    y=target,
    training_frame=train
)

print("AutoML Training Completed")

AutoML progress: |██
05:43:01.195: _min_rows param, The dataset size is too small to split for min_rows=100.0: must have at least 200.0 (weighted) rows, but have only 8.0.

█
05:43:03.768: _min_rows param, The dataset size is too small to split for min_rows=10.0: must have at least 20.0 (weighted) rows, but have only 8.0.
05:43:03.773: _min_rows param, The dataset size is too small to split for min_rows=10.0: must have at least 20.0 (weighted) rows, but have only 8.0.
05:43:03.774: _min_rows param, The dataset size is too small to split for min_rows=10.0: must have at least 20.0 (weighted) rows, but have only 8.0.

████████████████████████████████████████████████████████████| (done) 100%

05:43:20.25: StackedEnsemble_BestOfFamily_1_AutoML_1_20260811_54256 [StackedEnsemble best_of_family_xglm (built with AUTO metalearner, using top model from each algorithm type)] failed: java.lang.RuntimeException: water.exceptions.H2OIllegalArgumentException: Not enough data to create 5 random cross-validation splits. Either reduce nfolds, specify a larger dataset (or specify another random number seed, if applicable).
05:43:20.140: StackedEnsemble_AllModels_1_AutoML_1_20260811_54256 [StackedEnsemble all_xglm (built with AUTO metalearner, using all AutoML models)] failed: java.lang.RuntimeException: water.exceptions.H2OIllegalArgumentException: Not enough data to create 5 random cross-validation splits. Either reduce nfolds, specify a larger dataset (or specify another random number seed, if applicable).

AutoML Training Completed

In [11]:
leaderboard = automl.leaderboard

leaderboard

model_id                                             auc    logloss     aucpr    mean_per_class_error       rmse         mse
----------------------------------------------  --------  ---------  --------  ----------------------  ---------  ----------
GLM_1_AutoML_1_20260811_54256                   1         0.106802   1                            0    0.169975   0.0288914
DRF_1_AutoML_1_20260811_54256                   1         0.0557859  1                            0    0.127279   0.0162
GBM_5_AutoML_1_20260811_54256                   1         0          1                            0    0          0
GBM_grid_1_AutoML_1_20260811_54256_model_1      1         0.0186413  1                            0    0.0488917  0.0023904
XRT_1_AutoML_1_20260811_54256                   1         0.0525998  1                            0    0.0969211  0.00939371
DeepLearning_1_AutoML_1_20260811_54256          0.866667  2.43536    0.93834                      0.1  0.611399   0.373809
XGBoost_3_AutoML_1_20260811_54256               0.5       0.693147   0.625                        0.5  0.5        0.25
XGBoost_1_AutoML_1_20260811_54256               0.5       0.693147   0.625                        0.5  0.5        0.25
XGBoost_2_AutoML_1_20260811_54256               0.5       0.693147   0.625                        0.5  0.5        0.25
XGBoost_grid_1_AutoML_1_20260811_54256_model_1  0.3       0.703898   0.527391                     0.5  0.504221   0.254239
[10 rows x 7 columns]

In [12]:
best_model = automl.leader

best_model

Model Details
=============
H2OGeneralizedLinearEstimator : Generalized Linear Modeling
Model Key: GLM_1_AutoML_1_20260811_54256


GLM Model: summary
    family    link    regularization               lambda_search                                                                   number_of_predictors_total    number_of_active_predictors    number_of_iterations    training_frame
--  --------  ------  ---------------------------  ------------------------------------------------------------------------------  ----------------------------  -----------------------------  ----------------------  ----------------------------------------------
    binomial  logit   Ridge ( lambda = 0.004042 )  nlambda = 30, lambda.max = 40.422, lambda.min = 0.004042, lambda.1se = 0.03734  3                             3                              68                      AutoML_1_20260811_54256_training_py_2_sid_9429

ModelMetricsBinomialGLM: glm
** Reported on train data. **

MSE: 0.002889851948559254
RMSE: 0.05375734320592168
LogLoss: 0.03110111261612696
AUC: 1.0
AUCPR: 1.0
Gini: 1.0
Null degrees of freedom: 7
Residual degrees of freedom: 4
Null deviance: 10.585011810527714
Residual deviance: 0.4976178018580318
AIC: 8.497617801858032

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.8895059972555783
       Fail    Pass    Error    Rate
-----  ------  ------  -------  ---------
Fail   3       0       0        (0.0/3.0)
Pass   0       5       0        (0.0/5.0)
Total  3       5       0        (0.0/8.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value    idx
---------------------------  -----------  -------  -----
max f1                       0.889506     1        4
max f2                       0.889506     1        4
max f0point5                 0.889506     1        4
max accuracy                 0.889506     1        4
max precision                0.999997     1        0
max recall                   0.889506     1        4
max specificity              0.999997     1        0
max absolute_mcc             0.889506     1        4
max min_per_class_accuracy   0.889506     1        4
max mean_per_class_accuracy  0.889506     1        4
max tns                      0.999997     3        0
max fns                      0.999997     4        0
max fps                      0.00156797   3        7
max tps                      0.889506     5        4
max tnr                      0.999997     1        0
max fnr                      0.999997     0.8      0
max fpr                      0.00156797   1        7
max tpr                      0.889506     1        4

Gains/Lift Table: Avg response rate: 62.50 %, avg score: 62.50 %
group    cumulative_data_fraction    lower_threshold    lift    cumulative_lift    response_rate    score       cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain    cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  ------  -----------------  ---------------  ----------  --------------------------  ------------------  --------------  -------------------------  ------  -----------------  --------------------
1        0.125                       0.999996           1.6     1.6                1                0.999997    1                           0.999997            0.2             0.2                        60      60                 0.2
2        0.125                       0.999994           0       1.6                0                0           1                           0.999997            0               0.2                        -100    60                 0.2
3        0.125                       0.999993           0       1.6                0                0           1                           0.999997            0               0.2                        -100    60                 0.2
4        0.125                       0.999991           0       1.6                0                0           1                           0.999997            0               0.2                        -100    60                 0.2
5        0.125                       0.99999            0       1.6                0                0           1                           0.999997            0               0.2                        -100    60                 0.2
6        0.125                       0.999982           0       1.6                0                0           1                           0.999997            0               0.2                        -100    60                 0.2
7        0.25                        0.999956           1.6     1.6                1                0.999976    1                           0.999986            0.2             0.4                        60      60                 0.4
8        0.25                        0.999821           0       1.6                0                0           1                           0.999986            0               0.4                        -100    60                 0.4
9        0.375                       0.998904           1.6     1.6                1                0.999588    1                           0.999854            0.2             0.6                        60      60                 0.6
10       0.375                       0.994121           0       1.6                0                0           1                           0.999854            0               0.6                        -100    60                 0.6
11       0.5                         0.94113            1.6     1.6                1                0.992754    1                           0.998079            0.2             0.8                        60      60                 0.8
12       0.625                       0.732272           1.6     1.6                1                0.889506    1                           0.976364            0.2             1                          60      60                 1
13       0.625                       0.181954           0       1.6                0                0           1                           0.976364            0               1                          -100    60                 1
14       0.75                        0.0492995          0       1.33333            0                0.103337    0.833333                    0.83086             0               1                          -100    33.3333            0.666667
15       0.875                       0.00976258         0       1.14286            0                0.0132746   0.714286                    0.714062            0               1                          -100    14.2857            0.333333
16       1                           0.00156797         0       1                  0                0.00156797  0.625                       0.625               0               1                          -100    0                  0

ModelMetricsBinomialGLM: glm
** Reported on cross-validation data. **

MSE: 0.028891449204436686
RMSE: 0.1699748487407378
LogLoss: 0.10680232120427884
AUC: 1.0
AUCPR: 1.0
Gini: 1.0
Null degrees of freedom: 7
Residual degrees of freedom: 4
Null deviance: 11.262927532399335
Residual deviance: 1.7088371392684614
AIC: 9.70883713926846

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.620841832836433
       Fail    Pass    Error    Rate
-----  ------  ------  -------  ---------
Fail   3       0       0        (0.0/3.0)
Pass   0       5       0        (0.0/5.0)
Total  3       5       0        (0.0/8.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value    idx
---------------------------  -----------  -------  -----
max f1                       0.620842     1        4
max f2                       0.620842     1        4
max f0point5                 0.620842     1        4
max accuracy                 0.620842     1        4
max precision                0.999996     1        0
max recall                   0.620842     1        4
max specificity              0.999996     1        0
max absolute_mcc             0.620842     1        4
max min_per_class_accuracy   0.620842     1        4
max mean_per_class_accuracy  0.620842     1        4
max tns                      0.999996     3        0
max fns                      0.999996     4        0
max fps                      0.00139584   3        7
max tps                      0.620842     5        4
max tnr                      0.999996     1        0
max fnr                      0.999996     0.8      0
max fpr                      0.00139584   1        7
max tpr                      0.620842     1        4

Gains/Lift Table: Avg response rate: 62.50 %, avg score: 61.53 %
group    cumulative_data_fraction    lower_threshold    lift    cumulative_lift    response_rate    score       cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain    cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  ------  -----------------  ---------------  ----------  --------------------------  ------------------  --------------  -------------------------  ------  -----------------  --------------------
1        0.125                       0.999994           1.6     1.6                1                0.999996    1                           0.999996            0.2             0.2                        60      60                 0.2
2        0.125                       0.999992           0       1.6                0                0           1                           0.999996            0               0.2                        -100    60                 0.2
3        0.125                       0.99999            0       1.6                0                0           1                           0.999996            0               0.2                        -100    60                 0.2
4        0.125                       0.999989           0       1.6                0                0           1                           0.999996            0               0.2                        -100    60                 0.2
5        0.125                       0.999987           0       1.6                0                0           1                           0.999996            0               0.2                        -100    60                 0.2
6        0.125                       0.999978           0       1.6                0                0           1                           0.999996            0               0.2                        -100    60                 0.2
7        0.25                        0.999954           1.6     1.6                1                0.999971    1                           0.999983            0.2             0.4                        60      60                 0.4
8        0.25                        0.99984            0       1.6                0                0           1                           0.999983            0               0.4                        -100    60                 0.4
9        0.375                       0.99864            1.6     1.6                1                0.999644    1                           0.99987             0.2             0.6                        60      60                 0.6
10       0.375                       0.991606           0       1.6                0                0           1                           0.99987             0               0.6                        -100    60                 0.6
11       0.5                         0.805219           1.6     1.6                1                0.989597    1                           0.997302            0.2             0.8                        60      60                 0.8
12       0.625                       0.555668           1.6     1.6                1                0.620842    1                           0.92201             0.2             1                          60      60                 1
13       0.625                       0.32756            0       1.6                0                0           1                           0.92201             0               1                          -100    60                 1
14       0.75                        0.127499           0       1.33333            0                0.294973    0.833333                    0.817504            0               1                          -100    33.3333            0.666667
15       0.875                       0.0115131          0       1.14286            0                0.015849    0.714286                    0.702982            0               1                          -100    14.2857            0.333333
16       1                           0.00139584         0       1                  0                0.00139584  0.625                       0.615283            0               1                          -100    0                  0

Cross-Validation Metrics Summary:
                      mean         sd           cv_1_valid     cv_2_valid     cv_3_valid    cv_4_valid    cv_5_valid
--------------------  -----------  -----------  -------------  -------------  ------------  ------------  -------------
accuracy              1.0          0.0          1.0            1.0            1.0           1.0           1.0
aic                   8.375717     0.5112955    8.003505       8.032011       8.699047      9.123106      8.020916
auc                   1.0          0.0          1.0            1.0            1.0           1.0           1.0
err                   0.0          0.0          0.0            0.0            0.0           0.0           0.0
err_count             0.0          0.0          0.0            0.0            0.0           0.0           0.0
f0point5              1.0          0.0          1.0            1.0            1.0           1.0           1.0
f1                    1.0          0.0          1.0            1.0            1.0           1.0           1.0
f2                    1.0          0.0          1.0            1.0            1.0           1.0           1.0
lift_top_group        1.6          0.5477226    2.0            2.0            2.0           1.0           1.0
loglikelihood         0.0          0.0          0.0            0.0            0.0           0.0           0.0
---                   ---          ---          ---            ---            ---           ---           ---
mean_per_class_error  0.0          0.0          0.0            0.0            0.0           0.0           0.0
mse                   0.045672413  0.079919234  1.0374475e-06  0.00012559601  0.04350459    0.1846226     0.00010823179
null_deviance         2.2525854    1.0346059    3.0081549      3.0081549      3.0081549     1.1192316     1.1192316
pr_auc                1.0          0.0          1.0            1.0            1.0           1.0           1.0
precision             1.0          0.0          1.0            1.0            1.0           1.0           1.0
r2                    -inf         nan          0.9999958      0.9994976      0.8259816     -inf          -inf
recall                1.0          0.0          1.0            1.0            1.0           1.0           1.0
residual_deviance     0.37571704   0.5112955    0.0035051436   0.03201073     0.6990475     1.123106      0.02091589
rmse                  0.13217677   0.18775554   0.0010185516   0.011206962    0.20857754    0.42967734    0.010403451
specificity           1.0          0.0          1.0            1.0            1.0           nan           nan
[24 rows x 8 columns]


Scoring History:
     timestamp            duration    iteration    lambda    predictors    deviance_train        deviance_xval        deviance_se           alpha    iterations    training_rmse        training_logloss     training_r2         training_auc    training_pr_auc    training_lift    training_classification_error
---  -------------------  ----------  -----------  --------  ------------  --------------------  -------------------  --------------------  -------  ------------  -------------------  -------------------  ------------------  --------------  -----------------  ---------------  -------------------------------
     2026-08-11 05:43:01  0.000 sec   2            .4E2      4             1.3006578055421147    1.336880570128149    0.08923648196665271   0.0
     2026-08-11 05:43:01  0.001 sec   4            .29E2     4             1.2925136986881172    1.332018923419669    0.08740622442585326   0.0
     2026-08-11 05:43:01  0.002 sec   6            .21E2     4             1.2815447396638175    1.3254571504737653   0.08494886089235355   0.0
     2026-08-11 05:43:01  0.003 sec   8            .16E2     4             1.2668755553551823    1.316612864167578    0.0816616816351902    0.0
     2026-08-11 05:43:01  0.004 sec   10           .11E2     4             1.2474461908611263    1.3047502242802829   0.07730096599078093   0.0
     2026-08-11 05:43:01  0.004 sec   12           .83E1     4             1.222040894439617     1.2890116284892694   0.07161141976108157   0.0
     2026-08-11 05:43:01  0.007 sec   14           .6E1      4             1.189343095211613     1.268383628550724    0.06435645767776674   0.0
     2026-08-11 05:43:01  0.008 sec   16           .44E1     4             1.1481955475342815    1.2417631597684422   0.05542885205563487   0.0
     2026-08-11 05:43:01  0.009 sec   18           .32E1     4             1.0977769785316536    1.2081441734810419   0.045192750339024396  0.0
     2026-08-11 05:43:01  0.010 sec   20           .23E1     4             1.038010904435512     1.1668084051572674   0.03539121267603879   0.0
---  ---                  ---         ---          ---       ---           ---                   ---                  ---                   ---      ---           ---                  ---                  ---                 ---             ---                ---              ---
     2026-08-11 05:43:01  0.024 sec   44           .51E-1    4             0.25770811351573103   0.4765683999909471   0.19156526791633685   0.0
     2026-08-11 05:43:01  0.026 sec   47           .37E-1    4             0.22100787452053905   0.4370422428577945   0.1960666558809927    0.0
     2026-08-11 05:43:01  0.027 sec   50           .27E-1    4             0.18843654685893244   0.4017620603924986   0.19866715543526492   0.0
     2026-08-11 05:43:01  0.030 sec   53           .2E-1     4             0.15961893263333007   0.3706894484208231   0.19951715905749987   0.0
     2026-08-11 05:43:01  0.031 sec   56           .14E-1    4             0.1342602196744221    0.3437022525802895   0.1987520356485014    0.0
     2026-08-11 05:43:01  0.032 sec   59           .1E-1     4             0.11209633094211857   0.3205036969811683   0.19652173135494821   0.0
     2026-08-11 05:43:01  0.033 sec   62           .76E-2    4             0.09284972400579697   0.30059874808103704  0.19303226129425752   0.0
     2026-08-11 05:43:01  0.033 sec   65           .56E-2    4             0.0762932688857581    0.28340116133577953  0.18853057629730935   0.0
     2026-08-11 05:43:01  0.034 sec   68           .4E-2     4             0.06220222523225397   0.2683110883261016   0.1832758267989584    0.0
     2026-08-11 05:43:01  0.035 sec   70           .0E0      4             0.007757283521916701  0.0                  0.0                   0.0      70            0.05375734320592168  0.03110111261612696  0.9876699650194806  1.0             1.0                1.6              0.0
[31 rows x 18 columns]


Variable Importances:
variable        relative_importance    scaled_importance    percentage
--------------  ---------------------  -------------------  ------------
internal_marks  2.86569                1                    0.404173
attendance      2.42233                0.845285             0.341641
study_hours     1.80224                0.628902             0.254185

[tips]

In [13]:
import pandas as pd
import random

data = []

for i in range(100):

    study_hours = random.randint(1, 10)
    attendance = random.randint(50, 100)
    internal_marks = random.randint(35, 100)

    if (study_hours >= 5 and attendance >= 75 and internal_marks >= 60):
        result = "Pass"
    else:
        result = "Fail"

    data.append([
        study_hours,
        attendance,
        internal_marks,
        result
    ])

df = pd.DataFrame(
    data,
    columns=[
        "study_hours",
        "attendance",
        "internal_marks",
        "result"
    ]
)

df.to_csv("dataset.csv", index=False)

df.head()

   study_hours  attendance  internal_marks result
0           10          52              57   Fail
1            2          55              98   Fail
2            4          55              65   Fail
3            3          80              51   Fail
4            7         100              51   Fail

In [14]:
data = pd.read_csv("dataset.csv")

h2o_data = h2o.H2OFrame(data)

h2o_data["result"] = h2o_data["result"].asfactor()

h2o_data.head()

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

  study_hours    attendance    internal_marks  result
-------------  ------------  ----------------  --------
           10            52                57  Fail
            2            55                98  Fail
            4            55                65  Fail
            3            80                51  Fail
            7           100                51  Fail
            9            84                82  Pass
            1            52                60  Fail
            2            70                82  Fail
            4            61                74  Fail
            6            98                68  Pass
[10 rows x 4 columns]

In [15]:
train, test = h2o_data.split_frame(
    ratios=[0.8],
    seed=42
)

print("Train:", train.shape)
print("Test:", test.shape)

Train: (82, 4)
Test: (18, 4)

In [16]:
from h2o.automl import H2OAutoML

features = [
    "study_hours",
    "attendance",
    "internal_marks"
]

target = "result"

automl = H2OAutoML(
    max_models=10,
    seed=42,
    max_runtime_secs=120
)

automl.train(
    x=features,
    y=target,
    training_frame=train
)

print("AutoML Training Completed")

AutoML progress: |█
05:45:00.96: _min_rows param, The dataset size is too small to split for min_rows=100.0: must have at least 200.0 (weighted) rows, but have only 82.0.

██████████████████████████████████████████████████████████████| (done) 100%
AutoML Training Completed

In [17]:
leaderboard = automl.leaderboard

leaderboard

model_id                                                     auc    logloss     aucpr    mean_per_class_error      rmse        mse
------------------------------------------------------  --------  ---------  --------  ----------------------  --------  ---------
GBM_2_AutoML_2_20260811_54458                           0.999132  0.0677255  0.996996               0.0078125  0.1418    0.0201071
GBM_4_AutoML_2_20260811_54458                           0.99566   0.0454468  0.987652               0.0277778  0.108796  0.0118365
StackedEnsemble_AllModels_1_AutoML_2_20260811_54458     0.994792  0.075744   0.985813               0.0277778  0.146281  0.0213981
StackedEnsemble_BestOfFamily_1_AutoML_2_20260811_54458  0.993056  0.09218    0.97882                0.0555556  0.169391  0.0286933
GBM_3_AutoML_2_20260811_54458                           0.988715  0.0967268  0.971247               0.0555556  0.166964  0.0278771
XRT_1_AutoML_2_20260811_54458                           0.987847  0.200255   0.958743               0.03125    0.239746  0.0574781
DRF_1_AutoML_2_20260811_54458                           0.97526   0.185741   0.930235               0.118924   0.23559   0.0555025
GLM_1_AutoML_2_20260811_54458                           0.954861  0.215943   0.867815               0.134549   0.268421  0.0720498
GBM_5_AutoML_2_20260811_54458                           0.953125  0.281218   0.887199               0.0824653  0.298476  0.0890877
XGBoost_3_AutoML_2_20260811_54458                       0.901042  0.322708   0.78955                0.182292   0.314082  0.0986475
[12 rows x 7 columns]

In [18]:
best_model = automl.leader

print("Best Model:")
print(best_model)

Best Model:
Model Details
=============
H2OGradientBoostingEstimator : Gradient Boosting Machine
Model Key: GBM_2_AutoML_2_20260811_54458


Model Summary:
    number_of_trees    number_of_internal_trees    model_size_in_bytes    min_depth    max_depth    mean_depth    min_leaves    max_leaves    mean_leaves
--  -----------------  --------------------------  ---------------------  -----------  -----------  ------------  ------------  ------------  -------------
    593                593                         71257                  2            4            2.98651       3             7             4.8516

ModelMetricsBinomial: gbm
** Reported on train data. **

MSE: 5.146632417717992e-21
RMSE: 7.174003357761963e-11
LogLoss: 3.539602080530062e-11
Mean Per-Class Error: 0.0
AUC: 1.0
AUCPR: 1.0
Gini: 1.0

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.9999999999928515
       Fail    Pass    Error    Rate
-----  ------  ------  -------  -----------
Fail   64      0       0        (0.0/64.0)
Pass   17      1       0.9444   (17.0/18.0)
Total  81      1       0.2073   (17.0/82.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       1            1         17
max f2                       1            1         17
max f0point5                 1            1         17
max accuracy                 1            1         17
max precision                1            1         0
max recall                   1            1         17
max specificity              1            1         0
max absolute_mcc             1            1         17
max min_per_class_accuracy   1            1         17
max mean_per_class_accuracy  1            1         17
max tns                      1            64        0
max fns                      1            17        0
max fps                      1e-19        64        57
max tps                      1            18        17
max tnr                      1            1         0
max fnr                      1            0.944444  0
max fpr                      1e-19        1         57
max tpr                      1            1         17

Gains/Lift Table: Avg response rate: 21.95 %, avg score: 21.95 %
group    cumulative_data_fraction    lower_threshold    lift      cumulative_lift    response_rate    score        cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  --------  -----------------  ---------------  -----------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------  --------------------
1        0.0121951                   1                  4.55556   4.55556            1                1            1                           1                   0.0555556       0.0555556                  355.556   355.556            0.0555556
2        0.0243902                   1                  4.55556   4.55556            1                1            1                           1                   0.0555556       0.111111                   355.556   355.556            0.111111
3        0.0365854                   1                  4.55556   4.55556            1                1            1                           1                   0.0555556       0.166667                   355.556   355.556            0.166667
4        0.0487805                   1                  4.55556   4.55556            1                1            1                           1                   0.0555556       0.222222                   355.556   355.556            0.222222
5        0.0609756                   1                  4.55556   4.55556            1                1            1                           1                   0.0555556       0.277778                   355.556   355.556            0.277778
6        0.109756                    1                  4.55556   4.55556            1                1            1                           1                   0.222222        0.5                        355.556   355.556            0.5
7        0.158537                    1                  4.55556   4.55556            1                1            1                           1                   0.222222        0.722222                   355.556   355.556            0.722222
8        0.207317                    1                  4.55556   4.55556            1                1            1                           1                   0.222222        0.944444                   355.556   355.556            0.944444
9        0.304878                    4.73348e-11        0.569444  3.28               0.125            0.125        0.72                        0.72                0.0555556       1                          -43.0556  228                0.890625
10       0.402439                    2.79265e-11        0         2.48485            0                3.86348e-11  0.545455                    0.545455            0               1                          -100      148.485            0.765625
11       0.5                         1.19946e-11        0         2                  0                1.86133e-11  0.439024                    0.439024            0               1                          -100      100                0.640625
12       0.597561                    3.63337e-12        0         1.67347            0                7.72027e-12  0.367347                    0.367347            0               1                          -100      67.3469            0.515625
13       0.695122                    5.46232e-15        0         1.4386             0                1.76085e-12  0.315789                    0.315789            0               1                          -100      43.8596            0.390625
14       1                           1e-19              0         1                  0                1e-19        0.219512                    0.219512            0               1                          -100      0                  0

ModelMetricsBinomial: gbm
** Reported on cross-validation data. **

MSE: 0.020107119175958532
RMSE: 0.1417995739625424
LogLoss: 0.06772551054077176
Mean Per-Class Error: 0.0078125
AUC: 0.9991319444444444
AUCPR: 0.9969962654849847
Gini: 0.9982638888888888

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.11282100506790595
       Fail    Pass    Error    Rate
-----  ------  ------  -------  ----------
Fail   63      1       0.0156   (1.0/64.0)
Pass   0       18      0        (0.0/18.0)
Total  63      19      0.0122   (1.0/82.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.112821     0.972973  8
max f2                       0.112821     0.989011  8
max f0point5                 0.148897     0.988372  6
max accuracy                 0.148897     0.987805  6
max precision                1            1         0
max recall                   0.112821     1         8
max specificity              1            1         0
max absolute_mcc             0.112821     0.965694  8
max min_per_class_accuracy   0.112821     0.984375  8
max mean_per_class_accuracy  0.112821     0.992188  8
max tns                      1            64        0
max fns                      1            7         0
max fps                      1e-19        64        58
max tps                      0.112821     18        8
max tnr                      1            1         0
max fnr                      1            0.388889  0
max fpr                      1e-19        1         58
max tpr                      0.112821     1         8

Gains/Lift Table: Avg response rate: 21.95 %, avg score: 20.47 %
group    cumulative_data_fraction    lower_threshold    lift      cumulative_lift    response_rate    score        cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  --------  -----------------  ---------------  -----------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------  --------------------
1        0.134146                    1                  4.55556   4.55556            1                1            1                           1                   0.611111        0.611111                   355.556   355.556            0.611111
2        0.158537                    0.942969           4.55556   4.55556            1                0.977508     1                           0.99654             0.111111        0.722222                   355.556   355.556            0.722222
3        0.207317                    0.147206           4.55556   4.55556            1                0.689914     1                           0.924393            0.222222        0.944444                   355.556   355.556            0.944444
4        0.304878                    0.0749806          0.569444  3.28               0.125            0.102444     0.72                        0.661369            0.0555556       1                          -43.0556  228                0.890625
5        0.402439                    0.00806301         0         2.48485            0                0.0271842    0.545455                    0.507627            0               1                          -100      148.485            0.765625
6        0.5                         0.00012222         0         2                  0                0.00424836   0.439024                    0.409407            0               1                          -100      100                0.640625
7        1                           0                  0         1                  0                9.02146e-06  0.219512                    0.204708            0               1                          -100      0                  0

Cross-Validation Metrics Summary:
                         mean         sd           cv_1_valid    cv_2_valid    cv_3_valid     cv_4_valid    cv_5_valid
-----------------------  -----------  -----------  ------------  ------------  -------------  ------------  ------------
accuracy                 0.9882353    0.026306681  1.0           0.9411765     1.0            1.0           1.0
aic                      nan          0.0          nan           nan           nan            nan           nan
auc                      0.98         0.04472136   1.0           0.9           1.0            1.0           1.0
err                      0.011764706  0.026306681  0.0           0.05882353    0.0            0.0           0.0
err_count                0.2          0.4472136    0.0           1.0           0.0            0.0           0.0
f0point5                 0.96666664   0.0745356    1.0           0.8333333     1.0            1.0           1.0
f1                       0.93333334   0.1490712    1.0           0.6666667     1.0            1.0           1.0
f2                       0.9111111    0.1987616    1.0           0.5555556     1.0            1.0           1.0
lift_top_group           5.233333     2.1781745    5.6666665     8.5           5.3333335      4.0           2.6666667
loglikelihood            nan          0.0          nan           nan           nan            nan           nan
---                      ---          ---          ---           ---           ---            ---           ---
mcc                      0.93693066   0.14102738   1.0           0.6846532     1.0            1.0           1.0
mean_per_class_accuracy  0.95         0.1118034    1.0           0.75          1.0            1.0           1.0
mean_per_class_error     0.05         0.1118034    0.0           0.25          0.0            0.0           0.0
mse                      0.020163065  0.027662003  3.62528e-33   0.052818757   1.2627937e-29  0.04799657    6.23046e-17
pr_auc                   0.93305695   0.14968924   1.0           0.6652847     1.0            1.0           1.0
precision                1.0          0.0          1.0           1.0           1.0            1.0           1.0
r2                       0.8470395    0.22772823   1.0           0.4911793     1.0            0.7440183     1.0
recall                   0.9          0.2236068    1.0           0.5           1.0            1.0           1.0
rmse                     0.089780904  0.12299621   6.02103e-17   0.22982332    3.553581e-15   0.2190812     7.893326e-09
specificity              1.0          0.0          1.0           1.0           1.0            1.0           1.0
[22 rows x 8 columns]


Scoring History:
     timestamp            duration    number_of_trees    training_rmse           training_logloss        training_auc        training_pr_auc      training_lift      training_classification_error
---  -------------------  ----------  -----------------  ----------------------  ----------------------  ------------------  -------------------  -----------------  -------------------------------
     2026-08-11 05:45:08  6.281 sec   0.0                0.41391616459700326     0.526289869494131       0.5                 0.21951219512195122  1.0                0.7804878048780488
     2026-08-11 05:45:08  6.286 sec   5.0                0.337487169332853       0.3758010295698842      1.0                 1.0                  4.555555555555555  0.0
     2026-08-11 05:45:08  6.291 sec   10.0               0.2747263641648512      0.28126685037358123     0.9991319444444444  0.9969962654849847   0.0                0.012195121951219513
     2026-08-11 05:45:08  6.297 sec   15.0               0.22466161124568507     0.21224058181839156     1.0                 1.0                  4.555555555555555  0.0
     2026-08-11 05:45:08  6.305 sec   20.0               0.18522832439225795     0.1620109803265245      1.0                 1.0                  4.555555555555555  0.0
     2026-08-11 05:45:08  6.312 sec   25.0               0.14456177899853176     0.11981470637488348     1.0                 1.0                  4.555555555555555  0.0
     2026-08-11 05:45:08  6.316 sec   30.0               0.11723054813785465     0.0938035260688536      1.0                 1.0                  4.555555555555555  0.0
     2026-08-11 05:45:08  6.321 sec   35.0               0.09725963371480202     0.07424483277709622     1.0                 1.0                  4.555555555555555  0.0
     2026-08-11 05:45:08  6.326 sec   40.0               0.08332615111996568     0.060786699549817295    1.0                 1.0                  4.555555555555555  0.0
     2026-08-11 05:45:08  6.333 sec   45.0               0.07178259516325537     0.050504670403312316    1.0                 1.0                  4.555555555555555  0.0
---  ---                  ---         ---                ---                     ---                     ---                 ---                  ---                ---
     2026-08-11 05:45:09  7.416 sec   550.0              3.7767180497552613e-10  1.9540689805097982e-10  1.0                 1.0                  4.555555555555555  0.0
     2026-08-11 05:45:09  7.423 sec   555.0              3.238192858979681e-10   1.6120861426087045e-10  1.0                 1.0                  4.555555555555555  0.0
     2026-08-11 05:45:09  7.430 sec   560.0              2.7381615128182467e-10  1.3514093371145613e-10  1.0                 1.0                  4.555555555555555  0.0
     2026-08-11 05:45:09  7.436 sec   565.0              2.2434107045633032e-10  1.1383835069530938e-10  1.0                 1.0                  4.555555555555555  0.0
     2026-08-11 05:45:09  7.443 sec   570.0              1.843421283891755e-10   9.330330006242922e-11   1.0                 1.0                  4.555555555555555  0.0
     2026-08-11 05:45:09  7.448 sec   575.0              1.5510123882445972e-10  7.692599810385692e-11   1.0                 1.0                  4.555555555555555  0.0
     2026-08-11 05:45:09  7.458 sec   580.0              1.2883979487827981e-10  6.386294475107428e-11   1.0                 1.0                  4.555555555555555  0.0
     2026-08-11 05:45:09  7.464 sec   585.0              1.0121372391875707e-10  5.0281789577234664e-11  1.0                 1.0                  4.555555555555555  0.0
     2026-08-11 05:45:09  7.472 sec   590.0              7.788294452002539e-11   3.8999436474592574e-11  1.0                 1.0                  4.555555555555555  0.0
     2026-08-11 05:45:09  7.479 sec   593.0              7.174003357761963e-11   3.539602080530062e-11   1.0                 1.0                  4.555555555555555  0.0
[120 rows x 10 columns]


Variable Importances:
variable        relative_importance    scaled_importance    percentage
--------------  ---------------------  -------------------  ------------
study_hours     21.8594                1                    0.383325
attendance      18.7424                0.857407             0.328665
internal_marks  16.424                 0.751346             0.28801

In [19]:
performance = best_model.model_performance(test)

print("Model evaluation completed")

Model evaluation completed

In [20]:
accuracy = performance.accuracy([0.5])[0][1]
precision = performance.precision([0.5])[0][1]
recall = performance.recall([0.5])[0][1]
f1_score = performance.F1([0.5])[0][1]

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1_score)

Could not find exact threshold 0.5; using closest threshold found 0.9999999058895452.
Could not find exact threshold 0.5; using closest threshold found 0.9999999058895452.
Could not find exact threshold 0.5; using closest threshold found 0.9999999058895452.
Could not find exact threshold 0.5; using closest threshold found 0.9999999058895452.
Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1 Score : 1.0

In [21]:
print("========== AutoML Results ==========")
print("Best Model :", best_model.model_id)
print("Accuracy   :", accuracy)
print("Precision  :", precision)
print("Recall     :", recall)
print("F1 Score   :", f1_score)

========== AutoML Results ==========
Best Model : GBM_2_AutoML_2_20260811_54458
Accuracy   : 1.0
Precision  : 1.0
Recall     : 1.0
F1 Score   : 1.0

In [22]:
results = pd.DataFrame({
    "Metric": [
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ],
    "Value": [
        accuracy,
        precision,
        recall,
        f1_score
    ]
})

results.to_csv("automl_results.csv", index=False)

results

      Metric  Value
0   Accuracy    1.0
1  Precision    1.0
2     Recall    1.0
3   F1 Score    1.0

In [23]:
model_path = h2o.save_model(
    model=best_model,
    path="automl_model",
    force=True
)

print("Model saved at:", model_path)

Model saved at: /content/automl_model/GBM_2_AutoML_2_20260811_54458

In [24]:
!ls -lh

total 16K
drwxr-xr-x 2 root root 4.0K Aug 11 05:46 automl_model
-rw-r--r-- 1 root root   64 Aug 11 05:46 automl_results.csv
-rw-r--r-- 1 root root 1.4K Aug 11 05:44 dataset.csv
drwxr-xr-x 1 root root 4.0K Jun  4 13:32 sample_data

In [25]:
sample = h2o.H2OFrame({
    "study_hours": [7],
    "attendance": [85],
    "internal_marks": [80]
})

prediction = best_model.predict(sample)

prediction

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
gbm prediction progress: |███████████████████████████████████████████████████████| (done) 100%

predict           Fail    Pass
---------  -----------  ------
Pass       5.94598e-11       1
[1 row x 3 columns]

In [26]:
import dagshub
import mlflow

dagshub.init(
    repo_owner="deshamonisricharan",
    repo_name="Skill_4",
    mlflow=True
)

mlflow.set_experiment("H2O_AutoML_Experiment")

print("DagsHub and MLflow configured successfully")

                                       ❗❗❗ AUTHORIZATION REQUIRED ❗❗❗

Output()

Open the following link in your browser to authorize the client:
https://dagshub.com/login/oauth/authorize?state=961c6ad8-2558-4707-9db3-945bdf8e0132&client_id=32b60ba385aa7cecf24046d8195a71c07dd345d9657977863b52e7748e0f0f28&middleman_request_id=cd5e26e0399b9fbeb939680be181f0fd11fb2ce60a9a51232a1f3373a187eac2

Accessing as deshamonisricharan

Initialized MLflow to track repo "deshamonisricharan/Skill_4"

Repository deshamonisricharan/Skill_4 initialized!

2026/08/11 05:51:24 INFO mlflow.tracking.fluent: Experiment with name 'H2O_AutoML_Experiment' does not exist. Creating a new experiment.

DagsHub and MLflow configured successfully

In [27]:
with mlflow.start_run():

    # Parameters
    mlflow.log_param(
        "algorithm",
        "H2O AutoML"
    )

    mlflow.log_param(
        "max_models",
        10
    )

    mlflow.log_param(
        "dataset",
        "student_performance"
    )

    # Metrics
    mlflow.log_metric(
        "accuracy",
        accuracy
    )

    mlflow.log_metric(
        "precision",
        precision
    )

    mlflow.log_metric(
        "recall",
        recall
    )

    mlflow.log_metric(
        "f1_score",
        f1_score
    )

print("MLflow logging completed")

🏃 View run rare-fly-762 at: https://dagshub.com/deshamonisricharan/Skill_4.mlflow/#/experiments/0/runs/be823bdc83e74c75a8dfc1ca5e03dc98
🧪 View experiment at: https://dagshub.com/deshamonisricharan/Skill_4.mlflow/#/experiments/0
MLflow logging completed

In [28]:
model_path = h2o.save_model(
    model=best_model,
    path="/content/automl_model",
    force=True
)

print("Model saved at:", model_path)

Model saved at: /content/automl_model/GBM_2_AutoML_2_20260811_54458

In [29]:
with mlflow.start_run():

    mlflow.log_artifact(
        model_path,
        artifact_path="model"
    )

print("Model artifact logged")

🏃 View run clumsy-hawk-411 at: https://dagshub.com/deshamonisricharan/Skill_4.mlflow/#/experiments/0/runs/8627d11fe7a74609a77accf87785b9ec
🧪 View experiment at: https://dagshub.com/deshamonisricharan/Skill_4.mlflow/#/experiments/0
Model artifact logged

In [30]:
new_data = h2o.H2OFrame(
    {
        "study_hours": [8],
        "attendance": [95],
        "internal_marks": [90]
    }
)

prediction = best_model.predict(new_data)

prediction

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
gbm prediction progress: |███████████████████████████████████████████████████████| (done) 100%

predict           Fail    Pass
---------  -----------  ------
Fail       3.10513e-10       1
[1 row x 3 columns]

In [31]:
results = pd.DataFrame(
    {
        "Model": ["H2O AutoML Best Model"],
        "Accuracy": [accuracy],
        "Precision": [precision],
        "Recall": [recall],
        "F1 Score": [f1_score]
    }
)

results.to_csv(
    "automl_results.csv",
    index=False
)

results

                   Model  Accuracy  Precision  Recall  F1 Score
0  H2O AutoML Best Model       1.0        1.0     1.0       1.0

In [32]:
!ls -la

total 28
drwxr-xr-x 1 root root 4096 Aug 11 05:46 .
drwxr-xr-x 1 root root 4096 Aug 11 05:37 ..
drwxr-xr-x 2 root root 4096 Aug 11 05:46 automl_model
-rw-r--r-- 1 root root   79 Aug 11 05:52 automl_results.csv
drwxr-xr-x 4 root root 4096 Jun  4 13:32 .config
-rw-r--r-- 1 root root 1363 Aug 11 05:44 dataset.csv
drwxr-xr-x 1 root root 4096 Jun  4 13:32 sample_data

In [33]:
from getpass import getpass

token = getpass("Enter DagsHub Token:")

Enter DagsHub Token:··········

In [34]:
!git clone https://deshamonisricharan:{token}@dagshub.com/deshamonisricharan/Skill_4.git

Cloning into 'Skill_4'...
warning: You appear to have cloned an empty repository.

In [35]:
%cd /content/Skill_4/

/content/Skill_4

In [36]:
!ls -la

total 12
drwxr-xr-x 3 root root 4096 Aug 11 05:57 .
drwxr-xr-x 1 root root 4096 Aug 11 05:57 ..
drwxr-xr-x 7 root root 4096 Aug 11 05:57 .git

In [37]:
!cp /content/dataset.csv .
!cp /content/automl_results.csv .

In [38]:
!ls -la

total 20
drwxr-xr-x 3 root root 4096 Aug 11 05:58 .
drwxr-xr-x 1 root root 4096 Aug 11 05:57 ..
-rw-r--r-- 1 root root   79 Aug 11 05:58 automl_results.csv
-rw-r--r-- 1 root root 1363 Aug 11 05:58 dataset.csv
drwxr-xr-x 7 root root 4096 Aug 11 05:57 .git

In [39]:
!git config user.name "SriCharan-2466"
!git config user.email "deshamonisricharan@gmail.com"

In [40]:
!git add dataset.csv automl_results.csv

In [41]:
!git status

On branch main

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   automl_results.csv
	new file:   dataset.csv

In [42]:
!git commit -m "Completed Skill Session 4 - H2O AutoML"

[main (root-commit) 35f06ae] Completed Skill Session 4 - H2O AutoML
 2 files changed, 103 insertions(+)
 create mode 100644 automl_results.csv
 create mode 100644 dataset.csv

In [43]:
!git push origin main

Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 2 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 859 bytes | 859.00 KiB/s, done.
Total 4 (delta 0), reused 0 (delta 0), pack-reused 0
To https://dagshub.com/deshamonisricharan/Skill_4.git
 * [new branch]      main -> main